reconstructed_file_env = r'D:\Knowledge\Graduation_Design\WorkSpace\Py_WorkPlace\reconstruct\fr1_cam\mesh.ply'
standard_ply_file_env = r'D:\Knowledge\Graduation_Design\WorkSpace\Py_WorkPlace\reconstruct\fr1_cam\mesh.ply'
# mkv1_file_env = r"D:\Knowledge\Graduation_Design\WorkSpace\Py_WorkPlace\dataset\data\concrete\output-6-master.mkv"
mkv1_file_env = r"D:\Knowledge\Graduation_Design\WorkSpace\Py_WorkPlace\dataset\data\final\output-5.mkv"
mkv2_file_env = r"D:\Knowledge\Graduation_Design\WorkSpace\Py_WorkPlace\dataset\data\concrete\output-6-sub.mkv"
# concrete_path = r"D:\Knowledge\Graduation_Design\WorkSpace\Py_WorkPlace\dataset\data\concrete"
concrete_path = r"D:\Knowledge\Graduation_Design\WorkSpace\Py_WorkPlace\dataset\data\final"
ksize = 5 # 中值滤波器大小
d = 9  # 邻域直径
sigma_color = 75  # 颜色空间标准差
sigma_space = 75  # 坐标空间标准差
REMOTE = False